### Get
GET http://localhost:3001/members

### Create
POST http://localhost:3001/members
Content-Type: application/json

{
    "name" : "Test-name",
    "lastname": "Test-lastname",
    "position": "Test-position"
}

### Update
PUT http://localhost:3001/members/68ae9e9f70a2b723950ecf12
Content-Type: application/json

{
    "name" : "Test-name2",
    "lastname": "Test-lastname2",
    "position": "Test-position2"
}

### Delete
DELETE http://localhost:3001/members/68ae9df470a2b723950ecf10



